WIP: Add standard decorators docs
lit/lit.dev pull request #1176
Opened 2023-08-18 22:21 UTC by justinfagnani

2023-08-28 21:12 UTC, e111077 requested changes

2023-08-28 21:12 UTC, e111077 commented on packages/lit-dev-content/site/docs/v3/components/decorators.md
> +Because the implementations of "standard decorators" are new, this documented focuses on what we're calling "legacy" decorators, which we will refer to here as just "decorators". Future versions of L
"this documented" -> "this document"

2023-08-28 21:12 UTC, e111077 commented on packages/lit-dev-content/site/docs/v3/components/decorators.md
> +The standard decorators are a breaking change from the legacy decorators. Partially because of changes required by the new spec, like `accessor` and partially because the new spec allows us to implem
This paragraph deviates from the H3, please reintroduce the list. e.g. `The differences are:`

2023-08-28 21:12 UTC, e111077 commented on packages/lit-dev-content/site/docs/v3/components/decorators.md
> +* queryAsync is removed
queryAsync -> `queryAsync`

2023-08-28 21:12 UTC, e111077 commented on packages/lit-dev-content/site/docs/v3/components/decorators.md
> +* Import from `lit/std-decorators.js`, etc
I think people care more about "what does this mean for me?" Here can we emphasize the migration for users? idk if that should be a before / after table or just sub bullets here or maybe a different structure altogether

2023-08-28 21:12 UTC, e111077 commented on packages/lit-dev-content/site/docs/v3/components/decorators.md
> +Lit provides two implementations of decorators:
I think users care about "what does this mean for me". This is excellent information and it should stay, but we should maybe add a section of "which decorators should I use for my project? Should I be migrating?"

2023-08-29 04:55 UTC, AndrewJakubowicz commented
Noting down that this document will have to be updated to the hybrid decorators implementation: Where our decorators work in all environments.

2023-10-11 00:30 UTC, justinfagnani commented
Superseded by https://github.com/lit/lit.dev/pull/1218

2023-10-11 00:30 UTC, closed without merging