Update bundle URLs to `3.0.0`.
lit/lit.dev pull request #1217
Opened 2023-10-10 23:15 UTC by bicknellr

These are out of date as of today! 🎉 I specifically changed them to `3.0.0` rather than just `3` so that users that copy these URLs don't get surprised by the content changing out from under them when new minor and patch versions are released. If there's a way to dynamically reference the latest full version string, let me know and I'll update to that instead.

2023-10-10 23:20 UTC, AndrewJakubowicz approved these changes

2023-10-10 23:20 UTC, bicknellr commented on packages/lit-dev-content/site/docs/v3/getting-started.md
>        https://cdn.jsdelivr.net/gh/lit/dist@2/core/lit-core.min.js
I didn't update the actual link text!

2023-10-10 23:20 UTC, bicknellr commented on packages/lit-dev-content/site/docs/v3/getting-started.md
>        https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js
Also here

2023-10-10 23:21 UTC, AndrewJakubowicz approved these changes
They work great! Thank you for submitting this!

2023-10-10 23:21 UTC, AndrewJakubowicz commented on packages/lit-dev-content/site/docs/v3/getting-started.md
>        https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js
oh oops

2023-10-10 23:22 UTC, AndrewJakubowicz reviewed
It may be worth adding these to the `known-good-urls.txt` as well

2023-10-10 23:26 UTC, bicknellr commented on packages/lit-dev-content/site/docs/v3/getting-started.md
>        https://cdn.jsdelivr.net/gh/lit/dist@2/core/lit-core.min.js
fixed

2023-10-10 23:26 UTC, bicknellr commented on packages/lit-dev-content/site/docs/v3/getting-started.md
>        https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js
also fixed

2023-10-10 23:30 UTC, bicknellr commented
> It may be worth adding these links to the `known-good-urls.txt` as well

Added

2023-10-10 23:46 UTC, AndrewJakubowicz approved these changes

2023-10-11 01:04 UTC, augustjk requested changes
Thank you for catching this!

Maybe we should specify `@3` rather than `@3.0.0` so it stays relevant through the whole of Lit 3?

2023-10-11 01:04 UTC, augustjk commented on packages/lit-dev-content/site/docs/v3/getting-started.md
> +import {LitElement, html} from 'https://cdn.jsdelivr.net/gh/lit/dist@3.0.0/core/lit-core.min.js';
Do we maybe want to just specify major version here so users automatically get patches and minor non-breaking updates?
```suggestion
import {LitElement, html} from 'https://cdn.jsdelivr.net/gh/lit/dist@3/core/lit-core.min.js';
```

2023-10-11 20:36 UTC, augustjk approved these changes
Thank you!

2023-10-11 20:44 UTC, merged