Runtime warning docs
lit/lit.dev pull request #364
Opened 2021-05-06 16:03 UTC by justinfagnani

I realized we didn't mention these in the docs at all yet.

These aren't in great shape, but I wanted to put up the raw information in a PR at least.

2021-05-07 04:32 UTC, lazka commented
Does it state somewhere if these warnings are enabled by default? It's not clear to me based on this text.

2021-05-07 17:43 UTC, AndrewJakubowicz commented
@lazka From this [section on Development and Production builds](https://lit.dev/docs/tools/development/#development-and-production-builds), I believe you must opt into the development build.

2021-05-07 17:52 UTC, AndrewJakubowicz commented on packages/lit-dev-content/site/docs/tools/development.md
> +These methods are only available in development builds, so be sure to guard their access. We reccomend using optional chaining.
nitpick - typo
```suggestion
These methods are only available in development builds, so be sure to guard their access. We recommend using optional chaining.
```

2021-05-07 17:59 UTC, AndrewJakubowicz reviewed
Excellent! Left some minor syntax comments.

2021-05-07 17:59 UTC, AndrewJakubowicz commented on packages/lit-dev-content/site/docs/tools/development.md
> +ReactiveElement.disableWarning.?('migration');
typo - optional chaining call
```suggestion
ReactiveElement.disableWarning?.('migration');
```

2021-05-07 17:59 UTC, AndrewJakubowicz commented on packages/lit-dev-content/site/docs/tools/development.md
> +LitElement.disableWarning.?('change-in-update');
```suggestion
LitElement.disableWarning?.('change-in-update');
```

2021-05-07 17:59 UTC, AndrewJakubowicz commented on packages/lit-dev-content/site/docs/tools/development.md
> +MyElement.disableWarning.?('change-in-update');
```suggestion
MyElement.disableWarning?.('change-in-update');
```

2021-05-10 11:34 UTC, lazka commented
> @lazka From the section above on [Development and Production builds](https://lit.dev/docs/tools/development/#development-and-production-builds), I believe you must opt into the development build.

It also doesn't state if the warnings are enabled by default or not in the development build.

2021-07-09 19:49 UTC, arthurevans requested changes
Suggesting some edits.

2021-07-09 19:49 UTC, arthurevans commented on packages/lit-dev-content/site/docs/tools/development.md
> +* `'change-in-update'`: warnings related to changing reactive state during an update
```suggestion
* `'migration'`. Warnings related to migration from LitElement 2.x. Off by default.
* `'change-in-update'`. Warnings related to changing reactive state during an update. On by default.
```

2021-07-09 19:49 UTC, arthurevans commented on packages/lit-dev-content/site/docs/tools/development.md
> +// Disable migration warnings on all ReactiveElements,
```suggestion
// Turn off migration warnings on all ReactiveElements,
```

2021-07-09 19:49 UTC, arthurevans commented on packages/lit-dev-content/site/docs/tools/development.md
> +// Disable update warnings on all LitElements
```suggestion
// Turn off update warnings on all LitElements
```

2021-07-09 19:49 UTC, arthurevans commented on packages/lit-dev-content/site/docs/tools/development.md
> +// Disable update warnings on one element
```suggestion
// Turn off update warnings on one element
```

2021-07-09 19:49 UTC, arthurevans commented on packages/lit-dev-content/site/docs/tools/development.md
> +You can also control warnings within a single class with the `static enabledWarnings`:
Not 100% sure this is sounds good but the previous one isn't grammatical. (Also not sure whether having another way to do this really adds much utility.)

```suggestion
You can also control warnings within a single class by defining a `static enabledWarnings` property:
```

2021-09-07 16:29 UTC, justinfagnani commented
@arthurevans PTAL

2021-09-07 17:34 UTC, arthurevans commented on packages/lit-dev-content/site/docs/tools/development.md
> +:
```suggestion

```

Double colon here.

2021-09-07 17:36 UTC, arthurevans approved these changes
Made some last fixes, LGTM.

2021-09-07 18:22 UTC, merged