Cache external links that have worked
lit/lit.dev pull request #767
Opened 2022-04-21 20:41 UTC by rictic

This way, our CI doesn't fail if an external site is being flaky or rate limiting us, but we still check all of our internal links, and we check every new link that we add to the site.

2022-04-21 20:46 UTC, aomarks commented
One of the main ways we get 404s is links that worked when we first added them, but have since been moved or deleted. So won't this prevent us from noticing those cases?

2022-04-21 20:49 UTC, rictic commented
Hm, we could periodically clear the list

2022-04-22 00:53 UTC, aomarks commented
> Hm, we could periodically clear the list

As discussed offline, maybe a daily job that ignores this list. Ideally it would file a bug if it finds a problem (and update/delete it if the status changes independently of us doing anything).

But we can do that some other time. Maybe just file an issue?

This PR is good because we'll probably start paying attention to new failures, at least.

2022-04-22 00:53 UTC, aomarks requested changes

2022-04-22 19:26 UTC, rictic commented on packages/lit-dev-tests/src/check-broken-links.ts
> +import blc from 'broken-link-checker';
Done

2022-04-22 19:26 UTC, rictic commented on packages/lit-dev-tests/src/check-broken-links.ts
> +  console.error(e);
Done

2022-04-22 19:28 UTC, aomarks requested changes

2022-04-22 19:28 UTC, aomarks commented on packages/lit-dev-tests/src/check-broken-links.ts
> + * Copyright 2021 Google LLC
2022

2022-04-22 19:34 UTC, rictic commented on packages/lit-dev-tests/src/check-broken-links.ts
> + * Copyright 2021 Google LLC
Eep, yep!

2022-04-22 19:35 UTC, aomarks approved these changes

2022-04-22 20:08 UTC, merged